name: ElytraRace
author: Kyle Posluns
version: 1.0.0
description: Elytra Race hub minigame.
main: com.kyleposluns.elytrarace.ElytraRace
commands:
  elytrarace:
    description: Main Command for ElytraRace plugin!
    usage: /<command>